name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js from `.nvmrc`
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          # cache: 'pnpm'

      - name: Install dependencies & Build
        run: |
          corepack enable
          pnpm install
          pnpm run build

      - name: Run ESLint
        run: pnpm run lint

      - name: Run tests
        run: pnpm run --if-present test
